### ISSUE TITLE
Nested const values in refs won't render

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-entry-js#102]
**Describe the bug**
Nested consts inside of definitions won't render.

**To Reproduce**
1. Build a schema with a const in a defintion
2. Notice it doesn't render as read-only

**Expected behavior**
Consts should be readonly

**Additional context**
We should fix this in the uiSchema. Alternatively, there is a pr in the rjsf repo to fix this issue.

**Comment by helen-m-lin** [comment]
This is still an issue. Ongoing investigation.

Example: When selecting **Instrument > Objectives > Objective > Manufacturer**, all nested const values are showing as blank, even though the schema has default values for Name, Abbreviation, Registry name and abbr, and Registry Identifier.
![image](https://github.com/AllenNeuralDynamics/aind-metadata-entry-js/assets/46795546/204a9ec2-662b-4d78-ac84-bf595ca8156a)

**Comment by helen-m-lin** [comment]
@jtyoung84 Created a quick minimum example that can be viewed with https://rjsf-team.github.io/react-jsonschema-form/. For now, it seems that on the 3rd nested layer, const values start disappearing.

[min_example_const_issues.json](https://github.com/AllenNeuralDynamics/aind-metadata-entry-js/files/14608270/min_example_const_issues.json)
[min_example_const_issues_processed.json](https://github.com/AllenNeuralDynamics/aind-metadata-entry-js/files/14608271/min_example_const_issues_processed.json)
