### ISSUE TITLE
Incorrect default units

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-metadata-entry-js#112]
**Describe the bug**
Units with default units are defaulting to the wrong units. 

**To Reproduce**
1. Go to https://metadata-entry.allenneuraldynamics.org/
2. Select "rig" schema and scroll to Mouse Platform
3. Select Disc for mouse platform
4. See that default unit does not show up (supposed to be cm)

**Expected behavior**
The units rendered in the GUI should be defaulting as defined in aind-data-schema

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jtyoung84** [comment]
@mekhlakapoor Please add details

**Comment by mekhlakapoor** [comment]
This seems to be resolved. Default units are showing up as expected for entire rig schema (added devices and checked units for each). Also passed through a couple of the other schemas, and played around with versions. We can close this ticket once @jtyoung84 does a check

**Comment by jtyoung84** [comment]
I'll close this ticket. Helen spotted some issues with defaults in nested fields, but she's working on that in a separate ticket.
