### ISSUE TITLE
Render input fields for dictionaries

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-metadata-entry-js#113]
# User story
As a user, I want to be able to enter input and output parameters for unvalidated dictionaries. 

# Acceptance criteria
- [x] Given a field expecting dictionary, render input field for dictionary
- [x] Add a recursive function to go through schema

# Sprint Ready Checklist 
- [x] 1. Acceptance criteria defined 
- [x] 2. Team understands acceptance criteria 
- [x] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [x] 4. Acceptance criteria is verifiable / testable 
- [x] 5. External / 3rd Party dependencies identified
- [x] 6. Ticket is prioritized and sized

# Notes
is this always going to be pair values?

**Comment by helen-m-lin** [comment]
PR #151 will ensure that empty arrays `[]` aren't also included when checking for empty dicts `{}`
