### ISSUE TITLE
fix GUI issues associated with pydantic v2

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-metadata-entry-js#119]
# User story
As a user, I want to be able to use the app and fill out the form, so I can save my metadata.

# Acceptance criteria
- [x] Given a user selects a schema and any schema version, it should be rendered correctly on the screen.
- [x] Given the user fills out the form, they should be able to save it locally.

# Sprint Ready Checklist 
- [x] 1. Acceptance criteria defined 
- [x] 2. Team understands acceptance criteria 
- [x] 3. Team has defined solution / steps to satisfy acceptance criteria 
- [x] 4. Acceptance criteria is verifiable / testable 
- [x] 5. External / 3rd Party dependencies identified
- [x] 6. Ticket is prioritized and sized

# Notes
- latest schema versions do not render
- render Optional/ Nullable fields from schema as null on default
- should not display as Option 1, Option 2; instead display as Nullable/ Not Null
- future: fix issue with Discriminated/Tagged Unions

**Comment by jtyoung84** [comment]
Figure out what, if any, issues arise and create tickets to address them
