### ISSUE TITLE
Data description schema not rendering

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-metadata-entry-js#120]
**Describe the bug**
When the data description schema is selected, the app renders error message `Invalid regular expression: /^[^<>:;"/|? \_]+$/u: Invalid escape`

UPDATE: the form renders, but fails validation during submission with the same error. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by helen-m-lin** [comment]
Note: This is affecting all data_description schemas >= 0.12.0 (currently 0.13.6).

**Comment by helen-m-lin** [comment]
PR in https://github.com/AllenNeuralDynamics/aind-data-schema-models/pull/10 should fix the issue. @jtyoung84

**Comment by helen-m-lin** [comment]
This is now resolved as of data_description version 0.13.7
