### ISSUE TITLE
Validation shows false errors on entire subsections in select schemas

### ISSUE THREAD

**Issue by helen-m-lin** [AllenNeuralDynamics/aind-metadata-entry-js#139]
**Describe the bug**
When a user submits an incomplete form or a form with some errors, some schemas show errors on optional fields and other false positive errors.
- This is particularly noticed for `Rig` schemas where an incomplete `Mouse Platform` section would highlight every field as incorrect regardless of if it has errors. 
- However, if you complete the required fields (marked with a `*`), the validation errors for the entire section disappear.

**To Reproduce**
1. Go to https://metadata-entry.allenneuraldynamics-test.org/
2. Select `Rig` in the "Select schema" dropdown
3. [Optional] Fill out a few select fields, but making sure that some required fields are incomplete. 
4. Click the "Submit" button at the end of the form.
5. Observe that in addition to expected validation errors on incomplete required fields, most other optional fields are also displaying validation errors (see screenshot 1 below)
6. Resolve required fields (marked with `*`) in 1 sub-section only (e.g. enter Device name in `Mouse Platform`) while ignoring false positive errors on optional fields.
7. Observe that the false positive errors for that subsection disappear.

**Expected behavior**
There should not be false positive validation errors.

**Screenshots**
1. False positive errors on optional fields:
![image](https://github.com/AllenNeuralDynamics/aind-metadata-entry-js/assets/46795546/68956e29-1147-4134-988e-3b4431fa9736)

2. After filling out required fields, false errors disappear:
![image](https://github.com/AllenNeuralDynamics/aind-metadata-entry-js/assets/46795546/70136d26-9f44-442b-aea7-68f8bf749c90)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge, Chrome
 - Version: App version 0.1.6

**Additional context**
We should check all schemas to see if the same issue is occurring. Rig seems to be experiencing the most issues.

**Comment by jtyoung84** [comment]
We can try to pinpoint the underlying and timebox this to a few days at most

**Comment by helen-m-lin** [comment]
There were a few related issues causing validation errors:
1. On default, the Ajv validator does not have `discriminator` support enabled. Each individual field was being compared against all possible `oneOf` options rather than only currently selected, causing multiple errors under each field.
2. On default, Rjsf preserves previous form data after changing the selected option. This caused multiple `must NOT have additional properties` errors when the new option has a different schema and persisted incorrect values to the new schema.
3. There was a bug in our preprocessing logic that added `additionalProperties` to empty arrays. This caused additional `must NOT have additional properties` errors.

These issues are addressed in PR #151
