### ISSUE TITLE
Do not require users to choose a data type for Decimals

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-metadata-entry-js#148]
- [ ] Optional Decimal fields render as number, null dropdown
 - [ ] Decimal fields render as number
 - [ ] When a user saves the json file, the number fields are saved as strings. For example `"weight": "3.25"`
 - [ ] When a user loads a json file with a string input, it will fill in the field correctly

**Comment by mekhlakapoor** [comment]
@dyf can you add a description for what this means

**Comment by mekhlakapoor** [comment]
Right now, the app renders Decimal fields as a drop down. The data type defaults to 'null' with no input, and requires the user to select a data type (either string or number) to input a value. @dyf can you confirm whether this is the issue you're referring to?

![Image](https://github.com/AllenNeuralDynamics/aind-metadata-entry-js/assets/54870020/5e7d79c6-cb53-48bd-a1ea-e269ac6fe58a)


![Image](https://github.com/AllenNeuralDynamics/aind-metadata-entry-js/assets/54870020/c7edc8e2-72df-4e26-a00a-7c4ab7ff0034)
