### ISSUE TITLE
Add `mri_session` to the schemas filter list

### ISSUE THREAD

**Issue by helen-m-lin** [AllenNeuralDynamics/aind-metadata-entry-js#175]
**Is your feature request related to a problem? Please describe.**
MriSession has been removed from aind-data-schema core schemas. Historical JSON schemas are still in the S3 bucket and thus show up in the metadata entry app. Users should no longer see mri_session in the schemas dropdown.

**Describe the solution you'd like**
Add `mri_session` to the schemas filter list. This is the environment variable `REACT_APP_FILTER_SCHEMAS`. Update README with local dev instructions if needed.

**Describe alternatives you've considered**

**Additional context**

**Comment by mekhlakapoor** [comment]
Updated the env variable in amplify in dev. Don't have permissions to do so in prod.
