### ISSUE TITLE
Upgrade rjsf to >=5.18.6 and remove performance workaround

### ISSUE THREAD

**Issue by helen-m-lin** [AllenNeuralDynamics/aind-metadata-entry-js#179]
**Is your feature request related to a problem? Please describe.**
Previously we added a custom `omitExtraDataOnBlur` event handler as workaround for an RJSF `omitExtraData` bug (in PR #171). I contributed a fix to rjsf and it was released in v5.18.6.

**Describe the solution you'd like**
- Update RJSF version to >= 5.18.6
- Remove `omitExtraDataOnBlur` workaround
- Check performance issues are further improved
- Check update rjsf version does not break anything

**Describe alternatives you've considered**

**Additional context**

**Comment by micahwoodard** [comment]
@helen-m-lin do we want to update to the most recent release  5.19.4 or stick with 5.18.6?
