### ISSUE TITLE
Submit button requires multiple clicks

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-entry-js#26]
**Describe the bug**
It requires two clicks on Submit to save a form. The first click says certain fields are required even though they have been filled in correctly.

**To Reproduce**
1. Select `Subject`
2. Fill out some form data
3. Click Submit
5. Click Submit again and the form is saved correctly.

**Expected behavior**
If valid data is input, then the form should save correctly on the first click.

**Screenshots**
![Screenshot from 2022-10-11 09-37-03](https://user-images.githubusercontent.com/104453205/195150104-976979df-229f-449f-b258-fd1886d3abd6.png)

**Desktop (please complete the following information):**
 - OS: CentOS 7
 - Browser: Firefox
 - Version: 91.10.0esr (64-bit)

**Additional context**

**Comment by mekhlakapoor** [comment]
might be because of invalid schema type for validator: https://github.com/stoplightio/spectral/issues/403
- however, using ajv2020 or hyperjump still leads to same issue
-
