### ISSUE TITLE
Tech-debt, add unit test library and linters

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-entry-js#27]
# User story
As a developer, I want a clean and well-tested code-base, so I can maintain the code-base easier.

# Acceptance criteria
- [x] A command can be executed to run linters.
- [x] A command can be executed to run unit tests.
- [x] ~The test coverage should be 100%.~ Test coverage should not decrease.

# Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
2. - [x] Team understands acceptance criteria 
3. - [x] Team has defined solution / steps to satisfy acceptance criteria 
4. - [x] Acceptance criteria is verifiable / testable 
5. - [x] External / 3rd Party dependencies identified
6. - [x] Ticket is prioritized and sized

# Notes

**Comment by helen-m-lin** [comment]
@jtyoung84 @mekhlakapoor @dyf :
The `create-react-app` template comes with ESLint somewhat configured but I needed to add some setup to actually run it.
```
"eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
```
We should add ESLint's recommended rules (add `"extends": "eslint:recommended"`). Do we want to add any additional style guide?
> ? Which style guide do you want to follow? ...
> Airbnb: https://github.com/airbnb/javascript
  Standard: https://github.com/standard/standard
  Google: https://github.com/google/eslint-config-google        
  XO: https://github.com/xojs/eslint-config-xo

For your reference: https://betterprogramming.pub/comparing-the-top-three-style-guides-and-setting-them-up-with-eslint-98ea0d2fc5b7

**Comment by jtyoung84** [comment]
I'm cool with just using the Standard library
