### ISSUE TITLE
Fix dependency issue thrown by dependabot alert

### ISSUE THREAD

**Issue by mekhlakapoor** [AllenNeuralDynamics/aind-metadata-entry-js#32]
**Describe the bug**
Dependabot alert thrown: Inefficient Regular Expression Complexity in nth-check #1. 

**Screenshots**
<img width="943" alt="Screen Shot 2022-10-12 at 4 06 33 PM" src="https://user-images.githubusercontent.com/54870020/195463895-614199e4-a7c6-433b-b266-e4659ef0cb60.png">

**Comment by mekhlakapoor** [comment]
seems to be a false positive

**Comment by helen-m-lin** [comment]
@jtyoung84 @mekhlakapoor This specific alert has been dismissed https://github.com/AllenNeuralDynamics/aind-metadata-entry-js/security/dependabot/1, so I believe we can close this issue. 

However, there are 8 other dependabot alerts open in the repo; I've created #137 to track them.

**Comment by mekhlakapoor** [comment]
Closing this issue as it's been dismissed.
