### ISSUE TITLE
Remove underscores from default save filename

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-metadata-entry-js#63]

**Comment by mekhlakapoor** [comment]
i believe this is caused by the write_standard_file() method in aind-data-schema base.py

https://github.com/AllenNeuralDynamics/aind-data-schema/commit/7e38395e6e99f9c14d8a849ab41fb718a9143d6f#diff-ccfac95bd5a226da6fd06fdb8cece7bcd52f9f18dfa7bd034c182c0c1409eeae
