### ISSUE TITLE
Update schemas, including new `data_description.json`

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-metadata-entry-js#64]
This will include the `experiment_type`/`modality` change as well as the `name`/`abbreviation` change to `modality` and `instrument`. You will need to make a custom UI schema to handle the `name`/`abbreviation` change.

**Comment by mekhlakapoor** [comment]
ui-schema is difficult bc the schema itself, an easier workaround could be to preProcess the data_description schema to add the desired enumNames
