### ISSUE TITLE
Entering text is very laggy

### ISSUE THREAD

**Issue by galenlynch** [AllenNeuralDynamics/aind-metadata-entry-js#75]
The AIND metadata entry tool has about a 1 second lag for each character entered into a text box. This makes it unpleasant to use.  This is with ephys_rig schema 0.6.2.

**Comment by galenlynch** [comment]
It doesn't seem to be an issue with other schema.

**Comment by dyf** [comment]
@galenlynch which text box and which browser? I tried a couple in Chrome and didn't notice any lag.

**Comment by dyf** [comment]
I have seen this reported on the procedures schema as well.

**Comment by mekhlakapoor** [comment]
I have a feeling this is because of the size of the formData in state -- as the amount of data becomes more complex, it may take more time to update state. I need to re-check how often state is getting updated though

**Comment by galenlynch** [comment]
Sorry I created this and then ghosted. I tried on Windows 10 Enterprise (version 22H2) and Chrome (Version 114.0.5735.199 Official Build 64-bit) with any of our ephys2-rf schema (e.g. `\\allen\aind\scratch\ephys\metadata 2023-04-17\Update_2023-05-12\ephys_rig_323_EPHYS2-RF_2023-03-17_01.json`) using ephys_rig schema `0.6.2`. When I set the schema version to `0.7.1` the lag is still around one second. I don't know how to check the version of the metadata entry app but when I inspect the page source it looks like it's loading [/static/js/main.2bd5f9e7.js](https://neural-dynamics-dev.uw.r.appspot.com/static/js/main.2bd5f9e7.js).

The computer specs is i9-12900K 3.20 GHz with 128 GB RAM etc... hopefully should be beefy enough for data entry.

**Comment by galenlynch** [comment]
@dyf Sorry I noticed you also asked which text box showed this lag. It seems to be all of them. Right now I just tested Rig ID and Ephys Assembly Name, Scope assembly name (under "StickMicroscopeAssembly") and they all had ~1 second lag. Basically anything I test is slow.

**Comment by mekhlakapoor** [comment]
might've been fixed with #93 (removed validation)

**Comment by jtyoung84** [comment]
Follow up if this is finished

**Comment by jtyoung84** [comment]
@galenlynch We deployed the latest version of the app which should resolve the issue. We removed an option that validated the form on every text input. The form is only validated when a user hits the submit button.

**Comment by jtyoung84** [comment]
Looks like this has been resolved with the latest deployment
