### ISSUE TITLE
using entry app in Linux makes empty files

### ISSUE THREAD

**Issue by saskiad** [AllenNeuralDynamics/aind-metadata-entry-js#79]
I think Yoni conveyed this to me, might have been Galen. But they fill out the form, but the resulting json is blank.

**Comment by jtyoung84** [comment]
Closing this for now. It's possible the original issue referred to something else, but I checked it on my Linux machine on Chrome, and it seems to work fine.

**Comment by jsiegle** [comment]
Confirming this works on Chrome, but *only* on Chrome (and not Chromium-based browsers like Brave). For me, when using anything other than Chrome, clicking the "Submit" button doesn't do anything.
