### ISSUE TITLE
Automatically run npm build and save package-lock file

### ISSUE THREAD

**Issue by jtyoung84** [AllenNeuralDynamics/aind-metadata-entry-js#96]
# User story
As a user, I want the build to automatic, so I can ensure it gets updated correctly.

# Acceptance criteria
- [x] The package-lock file is updated on a pull request

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified
6. - [ ] Ticket is prioritized and sized

# Notes
*Add any helpful notes here.*

**Comment by helen-m-lin** [comment]
Check github action: merge to prod should check version bump
